#!/bin/bash
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -t 4320
#SBATCH -p all
#SBATCH --mem=9000
#SBATCH --open-mode=append
#SBATCH --mail-type=END
#SBATCH --mail-user=phi.richter@iup.physik.uni-bremen.de

#export LBL_HOME=/home/phi.richter/radiative_transfer/lblrtm
module unuse /home/eb/modules/all
module unuse /home/eb/modules/LAMOS
module use /home/eb/modules/_legacy/all
module load Python
module load netcdf4-python
module load matplotlib

python3 RRTMG_Cloudnet.py $1 $2 /home/phi.richter/Data/CLOUDNET/GDAS1/ /home/phi.richter/Data/FLUXES/RRTMG_Cloudnet_ERA5_atm/ 0.98 0 0
#python3 RRTMG_ERA5_vert.py $1 $2 /home/phi.richter/Data/CLOUDNET/GDAS1/ /home/phi.richter/Data/FLUXES/RRTMG_Cloudnet_ERA5_vert_scaled/ 0.98 1 0 0
