#!/bin/bash
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -t 4320
#SBATCH -p all
#SBATCH --mem=9000
#SBATCH --open-mode=append
#SBATCH --mail-type=END
#SBATCH --mail-user=phi.richter@iup.physik.uni-bremen.de

#export LBL_HOME=/home/phi.richter/radiative_transfer/lblrtm
module unuse /home/eb/modules/all
module unuse /home/eb/modules/LAMOS
module use /home/eb/modules/_legacy/all
module load Python
module load netcdf4-python
module load matplotlib

python3 read_flux_files.py $1 $2
python3 average.py $2 60 $3 $4

#$1: Path of RRTMG Output
#$2: Name of the output file, 
#$3: Column where to find the date
#$4: Name of the output file containing the averaged results